### ISSUE TITLE
Help to create authorization header for url & 

### ISSUE THREAD

**Issue by mikeyg123** [bedrin/kerb4j#27]
Hi
I would like to use SpengoClient to create a context and create a header that I can use with an arbitrary HttpConnection or websocket connection
However the SpnegoClient constructor which takes LoginConfig supplier is protected.  This makes it very awkward.

Could you make this public?
Or perhaps provide a utility method which takes a config section name and a url and returns the token authorization header string.

This is my extremely brittle  workaround which will obviously have problems with modules

    private static SpnegoClient spnegoClientForLogin(String s) throws ReflectiveOperationException {
        Constructor<SpnegoClient> ctor = SpnegoClient.class.getDeclaredConstructor(Callable.class);
        ctor.setAccessible(true);
        return ctor.newInstance((Callable<LoginContext>) () -> {
            try {
                return new LoginContext(s);
            } catch (LoginException e) {
                throw new RuntimeException(e);
            }
        });
    }

     String authHeader = spnegoClientForLogin(sectionName).createContext(url).createTokenAsAuthorizationHeader();

Thank you

**Comment by bedrin** [comment]
Hi there!

Sorry - I've missed your question.

I can make it public. Just want to understand the use case.
Why cannot you use one of static mathods like `SpnegoClient.loginWithUsernameAndPassword()` or `SpnegoClient.loginWithKeyTab()` ?

Kerb4J was designed to hide the complexity of Kerberos by providing plain `SpnegoClient` / `SpengoContext` interfaces.
Why do you want to provide `LoginContext` ?

Cheers,
 Dima.

**Comment by mikeyg123** [comment]
Hi Thanks for your reply
I am provided with a jaas style login config file specified by the java.security.auth.login.config system property.  This file has a particular named section which I need to use.  The jaas file may require me to use either the user's ticket cache or a particular keytab file and principal.
Without parsing the jaas config myself I don't know which of the above methods to call.
Regards
MikeG

**Comment by bedrin** [comment]
Merged to develop. Fixed in 0.1.1

**Comment by bedrin** [comment]
0.1.1 pushed to Maven central
