### ISSUE TITLE
Spring Security 5 support

### ISSUE THREAD

**Issue by GyllingSW** [bedrin/kerb4j#29]
As the Spring Security Kerberos project (https://github.com/spring-projects/spring-security-kerberos) is lacking support, and this could be a more modern solution - I would like to see a release containing support for Spring Security 5 directly embeddable into a Spring boot 2.X project.

Currently when including kerb4j there is dependencies to Spring Security 3.X, 4.X and 5.X if included in a Spring Boot 2.X project. This is a recipe for disaster in a not so far future.

**Comment by bedrin** [comment]
Hi @GyllingSW 

Thanks for raising it.
I'll take a look on the weekend.

**Comment by GyllingSW** [comment]
Hi @bedrin,

I need an upgrade on this at the very latest in the end of July. If you need help, then I have some hours to put into this sponsored by two customers, that need an upgrade to existing Spring Boot projects currently using Spring Security Kerberos as framework for SSO.

**Comment by GyllingSW** [comment]
Hi @bedrin,

To ease your work - I have provided you with a PR on this subject. There is still a lot of possible work, so my take would be to go with small steps.

**Comment by bedrin** [comment]
Awesome - checking today

**Comment by bedrin** [comment]
Merged. Planned for 0.1.1 release

**Comment by bedrin** [comment]
0.1.1 pushed to Maven central
