### ISSUE TITLE
Unnecessary compile scope dependency on kerb-simplekdc drags in a lot of dependencies

### ISSUE THREAD

**Issue by aggregat4** [bedrin/kerb4j#35]
We use kerb4j successfully (thanks!) but the kerb4j-common library keeps coming up on thirdparty version and security issue reviews in our company. 

I looked into the dependencies and the very large dependency tree of kerb4j-common is caused by it dependending on `org.apache.kerby:kerb-simplekdc`. This appears to be a KDC test server implementation that has a bunch of additional dependencies.

kerb4j-common only needs these dependencies for unit tests.

I have locally cloned the kerb4j repository and and set the dependency to `<scope>test</scope>` for kerb4j-common and I have additionally added the dependency (as a test dependency) to the following projects:

- kerb4j-client
- kerb4j-server-spring-security
- kerb4j-server-tomcat

After this change, a `mvn clean install` on the current master version builds and tests fine.

**Comment by bedrin** [comment]
Thanks for reporting it! Happy to accept the PR if you want to get it released faster :) 
Otherwise I'll check later this week when I have time.

**Comment by aggregat4** [comment]
Done.

**Comment by bedrin** [comment]
Thanks for PR. I've merged it and released version 0.1.2
It has been published to Maven Central but might take an hour or two to become available
